version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafkaui:
    image: provectuslabs/kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"

  postgres:
    image: postgres:16-alpine
    build:
      context: ./services/postgres
    restart: always
    environment:
      POSTGRES_USER: VALDML
      POSTGRES_PASSWORD: PROJETOPA
      POSTGRES_DB: binance_data
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    build:
      context: ./services/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: VALENTIN.DORMEUIL.PRO@GMAIL.COM
      PGADMIN_DEFAULT_PASSWORD: PROJETOPA
    ports:
      - "5050:80"

  #producer:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  depends_on:
  #    - kafka
  #    - postgre
  #  environment:
  #    KAFKA_HOST: kafka:9092

  producer_ccxt:
    build:
      context: ./producers/ohlcv_5m
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVER=kafka:9092

  #consumer:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  depends_on:
  #    - kafka
  #    - postgre
  #  environment:
  #    KAFKA_HOST: kafka:9092

  consumer_ccxt:
    build:
      context: ./consumers/ohlcv_5m
    depends_on:
      - kafka
      - postgres
    environment:
      POSTGRES_DB: binance_data
      POSTGRES_USER: VALDML
      POSTGRES_PASSWORD: PROJETOPA
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      KAFKA_SERVER: kafka:9092
      KAFKA_TOPIC: Binance_trades

  aggregator:
    build:
      context: ./aggregators/trades
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: binance_data
      POSTGRES_USER: VALDML
      POSTGRES_PASSWORD: PROJETOPA
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./projet_opa:/app
    depends_on:
      - kafka
      - postgres
    command: ["sh", "-c", "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - postgres

volumes:
  postgres_data:
