# ml/ohlcv_5m/Dockerfile.train

FROM python:3.11-slim

WORKDIR /app

# Installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source
COPY train_model.py .

# Exécuter l'entraînement au démarrage
CMD ["python", "train_model.py"]
